/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.jumbo.frame;


import br.com.jumbo.controller.ColaboradorControler;
import br.com.jumbo.controller.ColaboradorDetalheController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Joao
 */
public class Colaborador extends InternalFrame {
    

    /**
     * Creates new form Carros
     */

        private Connection conn = null;

    public Colaborador(Connection conn, ColaboradorControler controller) {
        this.conn = conn;

        try {

            initComponents();
            setSize(500, 200);
            gridControl1.setController(controller);
            gridControl1.setGridDataLocator(controller);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void reloadData() {
        
        gridControl1.reloadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gridControl1 = new org.openswing.swing.client.GridControl();
        integerColumn1 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn7 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn8 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn9 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn10 = new org.openswing.swing.table.columns.client.TextColumn();
        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        jPanel2 = new javax.swing.JPanel();
        labelControl2 = new org.openswing.swing.client.LabelControl();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setFunctionId("colaborador");
        gridControl1.setInsertButton(insertButton1);
        gridControl1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl1.setValueObjectClassName("br.com.jumbo.vo.ColaboradorVO");

        integerColumn1.setColumnFilterable(true);
        integerColumn1.setColumnName("colId");
        integerColumn1.setColumnSortable(true);
        integerColumn1.setHeaderColumnName("Código ");
        gridControl1.getColumnContainer().add(integerColumn1);

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("colNome");
        textColumn1.setColumnSortable(true);
        textColumn1.setHeaderColumnName("Nome");
        textColumn1.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnFilterable(true);
        textColumn2.setColumnName("veiPlaca");
        textColumn2.setColumnSortable(true);
        textColumn2.setHeaderColumnName("Placa");
        textColumn2.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn2);

        textColumn3.setColumnFilterable(true);
        textColumn3.setColumnName("colEnd");
        textColumn3.setColumnSortable(true);
        textColumn3.setHeaderColumnName("Endereço");
        textColumn3.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn3);

        textColumn4.setColumnFilterable(true);
        textColumn4.setColumnName("colBairro");
        textColumn4.setColumnSortable(true);
        textColumn4.setHeaderColumnName("Bairro");
        gridControl1.getColumnContainer().add(textColumn4);

        textColumn5.setColumnFilterable(true);
        textColumn5.setColumnName("colCidade");
        textColumn5.setColumnSortable(true);
        textColumn5.setHeaderColumnName("Cidade");
        gridControl1.getColumnContainer().add(textColumn5);

        textColumn6.setColumnFilterable(true);
        textColumn6.setColumnName("colEst");
        textColumn6.setColumnSortable(true);
        textColumn6.setHeaderColumnName("Est");
        textColumn6.setPreferredWidth(70);
        textColumn6.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn6);

        textColumn7.setColumnDuplicable(true);
        textColumn7.setColumnFilterable(true);
        textColumn7.setColumnName("colFone1");
        textColumn7.setColumnSortable(true);
        textColumn7.setHeaderColumnName("Fone 1");
        textColumn7.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn7);

        textColumn8.setColumnFilterable(true);
        textColumn8.setColumnName("colFone2");
        textColumn8.setColumnSortable(true);
        textColumn8.setHeaderColumnName("Fone 2");
        gridControl1.getColumnContainer().add(textColumn8);

        textColumn9.setColumnFilterable(true);
        textColumn9.setColumnName("colCpf");
        textColumn9.setColumnSortable(true);
        textColumn9.setHeaderColumnName("CPF");
        gridControl1.getColumnContainer().add(textColumn9);

        textColumn10.setColumnFilterable(true);
        textColumn10.setColumnName("colRg");
        textColumn10.setColumnSortable(true);
        textColumn10.setHeaderColumnName("RG");
        textColumn10.setTextAlignment(SwingConstants.RIGHT);
        gridControl1.getColumnContainer().add(textColumn10);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        insertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(insertButton1);
        jPanel1.add(deleteButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        labelControl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelControl2.setLabel("Cadastro de Colaboradores");
        jPanel2.add(labelControl2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
        new ColaboradorDetalheController(this, null, conn);
    }//GEN-LAST:event_insertButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn10;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn7;
    private org.openswing.swing.table.columns.client.TextColumn textColumn8;
    private org.openswing.swing.table.columns.client.TextColumn textColumn9;
    // End of variables declaration//GEN-END:variables
}
