/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jumbo.frame;

import br.com.jumbo.controller.ColaboradorLookupController;
import br.com.jumbo.vo.VeiculoVO;
import java.sql.*;
import java.util.Collection;
import javax.swing.text.MaskFormatter;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.form.client.Form;
import org.openswing.swing.form.client.FormController;
import org.openswing.swing.lookup.client.LookupController;
import org.openswing.swing.lookup.client.LookupListener;
import org.openswing.swing.message.receive.java.ValueObject;

/**
 *
 * @author Joao
 */
public class PessoasDetalhe extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form VeiculoDetalhe
     */
    public PessoasDetalhe(Connection conn, FormController dataController) {
        try {
            this.conn = conn;
            initComponents();

            MaskFormatter fone1 = new MaskFormatter(" (##)####-####");
            MaskFormatter fone2 = new MaskFormatter(" (##)####-####");
            MaskFormatter cpf = new MaskFormatter(" ###.###.###-##");
            MaskFormatter data_nascimento = new MaskFormatter(" ##/##/#####");

            fone1.setValidCharacters("0123456789");
            fone2.setValidCharacters("0123456789");
            cpf.setValidCharacters("0123456789");
            data_nascimento.setValidCharacters("0123456789");

            formattedTextControl1.setFormatter(fone1);
            formattedTextControl2.setFormatter(fone2);
            formattedTextControl3.setFormatter(cpf);
            formattedTextControl4.setFormatter(data_nascimento);

            formattedTextControl1.setEnabled(true);
            formattedTextControl2.setEnabled(true);
            formattedTextControl3.setEnabled(true);
            formattedTextControl4.setEnabled(true);

            /*
             lookupController.addLookupListener(new LookupListener() {

             public void beforeLookupAction(ValueObject parentVO) {
             }

             public void codeChanged(ValueObject parentVO, Collection parentChangedAttributes) {
             VeiculoVO = (VeiculoVO) codLookupControl1.getLookupController().getLookupVO();
             }

             public void codeValidated(boolean validated) {
             }

             public void forceValidate() {
             }
             });
             */
            form1.setFormController(dataController);

            setSize(590, 440);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Form getForm1() {
        return form1;
    }

 //   public VeiculoDetalhe(Connection conn, VeiculoDetalheController aThis) {
    //       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        form1 = new org.openswing.swing.form.client.Form();
        textControl1 = new org.openswing.swing.client.TextControl();
        textControl2 = new org.openswing.swing.client.TextControl();
        textControl3 = new org.openswing.swing.client.TextControl();
        labelControl1 = new org.openswing.swing.client.LabelControl();
        labelControl2 = new org.openswing.swing.client.LabelControl();
        labelControl3 = new org.openswing.swing.client.LabelControl();
        labelControl4 = new org.openswing.swing.client.LabelControl();
        labelControl5 = new org.openswing.swing.client.LabelControl();
        labelControl6 = new org.openswing.swing.client.LabelControl();
        labelControl7 = new org.openswing.swing.client.LabelControl();
        labelControl8 = new org.openswing.swing.client.LabelControl();
        textControl7 = new org.openswing.swing.client.TextControl();
        labelControl9 = new org.openswing.swing.client.LabelControl();
        formattedTextControl1 = new org.openswing.swing.client.FormattedTextControl();
        formattedTextControl2 = new org.openswing.swing.client.FormattedTextControl();
        formattedTextControl3 = new org.openswing.swing.client.FormattedTextControl();
        comboBoxControl1 = new org.openswing.swing.client.ComboBoxControl();
        textControl5 = new org.openswing.swing.client.TextControl();
        labelControl10 = new org.openswing.swing.client.LabelControl();
        labelControl11 = new org.openswing.swing.client.LabelControl();
        formattedTextControl4 = new org.openswing.swing.client.FormattedTextControl();
        numericControl1 = new org.openswing.swing.client.NumericControl();
        jPanel1 = new javax.swing.JPanel();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        editButton1 = new org.openswing.swing.client.EditButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoas");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        form1.setVOClassName("br.com.jumbo.vo.PessoasVO");
        form1.setEditButton(editButton1);
        form1.setSaveButton(saveButton1);
        form1.setLayout(new java.awt.GridBagLayout());

        textControl1.setAttributeName("pesNome");
        textControl1.setEnabled(false);
        textControl1.setMaxCharacters(30);
        textControl1.setRequired(true);
        textControl1.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(textControl1, gridBagConstraints);

        textControl2.setAttributeName("pesEnd");
        textControl2.setEnabled(false);
        textControl2.setMaxCharacters(20);
        textControl2.setRequired(true);
        textControl2.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(textControl2, gridBagConstraints);

        textControl3.setAttributeName("pesBairro");
        textControl3.setEnabled(false);
        textControl3.setMaxCharacters(20);
        textControl3.setRequired(true);
        textControl3.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(textControl3, gridBagConstraints);

        labelControl1.setLabel("Endereço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        form1.add(labelControl1, gridBagConstraints);

        labelControl2.setLabel("Cidade");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        form1.add(labelControl2, gridBagConstraints);

        labelControl3.setLabel("Bairro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        form1.add(labelControl3, gridBagConstraints);

        labelControl4.setLabel("Fone 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(labelControl4, gridBagConstraints);

        labelControl5.setLabel("Fone 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(labelControl5, gridBagConstraints);

        labelControl6.setLabel("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        form1.add(labelControl6, gridBagConstraints);

        labelControl7.setText("Data Nascimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        form1.add(labelControl7, gridBagConstraints);

        labelControl8.setText("Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        form1.add(labelControl8, gridBagConstraints);

        textControl7.setAttributeName("pesCidade");
        textControl7.setEnabled(false);
        textControl7.setMaxCharacters(20);
        textControl7.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(textControl7, gridBagConstraints);

        labelControl9.setLabel("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        form1.add(labelControl9, gridBagConstraints);

        formattedTextControl1.setAttributeName("pesFone1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(formattedTextControl1, gridBagConstraints);

        formattedTextControl2.setAttributeName("pesFone2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        form1.add(formattedTextControl2, gridBagConstraints);

        formattedTextControl3.setAttributeName("pesCpf");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        form1.add(formattedTextControl3, gridBagConstraints);

        comboBoxControl1.setAttributeName("pesEst");
        comboBoxControl1.setDomainId("ESTADOS");
        comboBoxControl1.setEnabled(false);
        comboBoxControl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxControl1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        form1.add(comboBoxControl1, gridBagConstraints);

        textControl5.setAttributeName("pesRg");
        textControl5.setEnabled(false);
        textControl5.setMaxCharacters(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        form1.add(textControl5, gridBagConstraints);

        labelControl10.setLabel("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        form1.add(labelControl10, gridBagConstraints);

        labelControl11.setLabel("RG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        form1.add(labelControl11, gridBagConstraints);

        formattedTextControl4.setAttributeName("pesDataNasc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        form1.add(formattedTextControl4, gridBagConstraints);

        numericControl1.setAttributeName("pesNr");
        numericControl1.setEnabled(false);
        numericControl1.setMaxCharacters(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        form1.add(numericControl1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(form1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton1);
        jPanel1.add(editButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxControl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxControl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxControl1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.ComboBoxControl comboBoxControl1;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.form.client.Form form1;
    private org.openswing.swing.client.FormattedTextControl formattedTextControl1;
    private org.openswing.swing.client.FormattedTextControl formattedTextControl2;
    private org.openswing.swing.client.FormattedTextControl formattedTextControl3;
    private org.openswing.swing.client.FormattedTextControl formattedTextControl4;
    private javax.swing.JPanel jPanel1;
    private org.openswing.swing.client.LabelControl labelControl1;
    private org.openswing.swing.client.LabelControl labelControl10;
    private org.openswing.swing.client.LabelControl labelControl11;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.client.LabelControl labelControl3;
    private org.openswing.swing.client.LabelControl labelControl4;
    private org.openswing.swing.client.LabelControl labelControl5;
    private org.openswing.swing.client.LabelControl labelControl6;
    private org.openswing.swing.client.LabelControl labelControl7;
    private org.openswing.swing.client.LabelControl labelControl8;
    private org.openswing.swing.client.LabelControl labelControl9;
    private org.openswing.swing.client.NumericControl numericControl1;
    private org.openswing.swing.client.SaveButton saveButton1;
    private org.openswing.swing.client.TextControl textControl1;
    private org.openswing.swing.client.TextControl textControl2;
    private org.openswing.swing.client.TextControl textControl3;
    private org.openswing.swing.client.TextControl textControl5;
    private org.openswing.swing.client.TextControl textControl7;
    // End of variables declaration//GEN-END:variables
}
