/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.jumbo.frame;

import java.sql.*;

import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.form.client.Form;
import org.openswing.swing.form.client.FormController;

/**
 *
 * @author Joao
 */
public class VeiculoDetalhe extends InternalFrame {
    
     private Connection conn = null;

    /**
     * Creates new form VeiculoDetalhe
     */
    public VeiculoDetalhe(Connection conn, FormController dataController) {
         try {
            this.conn = conn;
        initComponents();
                
       
        
            
           

            
            
           
            
        
             form1.setFormController(dataController);

            setSize(590, 440);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
       public Form getForm1() {
        return form1;
    }
    

 //   public VeiculoDetalhe(Connection conn, VeiculoDetalheController aThis) {
 //       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 //   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        form1 = new org.openswing.swing.form.client.Form();
        dateControl1 = new org.openswing.swing.client.DateControl();
        textControl2 = new org.openswing.swing.client.TextControl();
        textControl3 = new org.openswing.swing.client.TextControl();
        textControl4 = new org.openswing.swing.client.TextControl();
        numericControl1 = new org.openswing.swing.client.NumericControl();
        numericControl2 = new org.openswing.swing.client.NumericControl();
        labelControl1 = new org.openswing.swing.client.LabelControl();
        labelControl2 = new org.openswing.swing.client.LabelControl();
        labelControl3 = new org.openswing.swing.client.LabelControl();
        labelControl4 = new org.openswing.swing.client.LabelControl();
        labelControl5 = new org.openswing.swing.client.LabelControl();
        labelControl6 = new org.openswing.swing.client.LabelControl();
        labelControl7 = new org.openswing.swing.client.LabelControl();
        textControl1 = new org.openswing.swing.client.TextControl();
        jPanel1 = new javax.swing.JPanel();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veíuculos");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        form1.setVOClassName("br.com.jumbo.vo.VeiculoVO");
        form1.setEditButton(editButton1);
        form1.setReloadButton(reloadButton1);
        form1.setSaveButton(saveButton1);
        form1.setLayout(new java.awt.GridBagLayout());

        dateControl1.setAttributeName("veiData");
        dateControl1.setEnabled(false);
        dateControl1.setLinkLabel(labelControl7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        form1.add(dateControl1, gridBagConstraints);

        textControl2.setAttributeName("veiMod");
        textControl2.setEnabled(false);
        textControl2.setLinkLabel(labelControl2);
        textControl2.setMaxCharacters(15);
        textControl2.setRequired(true);
        textControl2.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        form1.add(textControl2, gridBagConstraints);

        textControl3.setAttributeName("veiCor");
        textControl3.setEnabled(false);
        textControl3.setLinkLabel(labelControl4);
        textControl3.setMaxCharacters(15);
        textControl3.setRequired(true);
        textControl3.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        form1.add(textControl3, gridBagConstraints);

        textControl4.setAttributeName("veiMarca");
        textControl4.setEnabled(false);
        textControl4.setLinkLabel(labelControl1);
        textControl4.setMaxCharacters(15);
        textControl4.setRequired(true);
        textControl4.setUpperCase(true);
        textControl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textControl4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        form1.add(textControl4, gridBagConstraints);

        numericControl1.setAttributeName("veiAno");
        numericControl1.setEnabled(false);
        numericControl1.setLinkLabel(labelControl3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        form1.add(numericControl1, gridBagConstraints);

        numericControl2.setAttributeName("veiKm");
        numericControl2.setEnabled(false);
        numericControl2.setLinkLabel(labelControl5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        form1.add(numericControl2, gridBagConstraints);

        labelControl1.setLabel("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        form1.add(labelControl1, gridBagConstraints);

        labelControl2.setLabel("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        form1.add(labelControl2, gridBagConstraints);

        labelControl3.setLabel("Ano");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        form1.add(labelControl3, gridBagConstraints);

        labelControl4.setLabel("Cor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        form1.add(labelControl4, gridBagConstraints);

        labelControl5.setLabel("Km");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        form1.add(labelControl5, gridBagConstraints);

        labelControl6.setLabel("Placa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        form1.add(labelControl6, gridBagConstraints);

        labelControl7.setLabel("Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        form1.add(labelControl7, gridBagConstraints);

        textControl1.setAttributeName("veiPlaca");
        textControl1.setEnabled(false);
        textControl1.setLinkLabel(labelControl6);
        textControl1.setMaxCharacters(8);
        textControl1.setRequired(true);
        textControl1.setUpperCase(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        form1.add(textControl1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(form1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton1);
        jPanel1.add(editButton1);
        jPanel1.add(reloadButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textControl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textControl4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textControl4ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.DateControl dateControl1;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.form.client.Form form1;
    private javax.swing.JPanel jPanel1;
    private org.openswing.swing.client.LabelControl labelControl1;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.client.LabelControl labelControl3;
    private org.openswing.swing.client.LabelControl labelControl4;
    private org.openswing.swing.client.LabelControl labelControl5;
    private org.openswing.swing.client.LabelControl labelControl6;
    private org.openswing.swing.client.LabelControl labelControl7;
    private org.openswing.swing.client.NumericControl numericControl1;
    private org.openswing.swing.client.NumericControl numericControl2;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.client.SaveButton saveButton1;
    private org.openswing.swing.client.TextControl textControl1;
    private org.openswing.swing.client.TextControl textControl2;
    private org.openswing.swing.client.TextControl textControl3;
    private org.openswing.swing.client.TextControl textControl4;
    // End of variables declaration//GEN-END:variables
}
