/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.jumbo.frame;

import br.com.jumbo.controller.VeiculoDetalheController;
import br.com.jumbo.controller.VeiculoControler;

import java.sql.Connection;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Joao
 */
public class Veiculo extends InternalFrame {
    

    /**
     * Creates new form Carros
     */

        private Connection conn = null;

    public Veiculo(Connection conn, VeiculoControler controller) {
        this.conn = conn;

        try {

            initComponents();
            setSize(500, 200);
            gridControl1.setController(controller);
            gridControl1.setGridDataLocator(controller);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void reloadData() {
        
        gridControl1.reloadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gridControl1 = new org.openswing.swing.client.GridControl();
        integerColumn1 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        integerColumn2 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        integerColumn3 = new org.openswing.swing.table.columns.client.IntegerColumn();
        dateColumn1 = new org.openswing.swing.table.columns.client.DateColumn();
        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        jPanel2 = new javax.swing.JPanel();
        labelControl2 = new org.openswing.swing.client.LabelControl();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setFunctionId("veiculo");
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl1.setValueObjectClassName("br.com.jumbo.vo.VeiculoVO");

        integerColumn1.setColumnFilterable(true);
        integerColumn1.setColumnName("veiId");
        integerColumn1.setColumnSortable(true);
        integerColumn1.setHeaderColumnName("Código veiculo");
        gridControl1.getColumnContainer().add(integerColumn1);

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("veiMarca");
        textColumn1.setColumnSortable(true);
        textColumn1.setHeaderColumnName("Marca");
        textColumn1.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnFilterable(true);
        textColumn2.setColumnName("veiMod");
        textColumn2.setColumnSortable(true);
        textColumn2.setHeaderColumnName("Modelo");
        textColumn2.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn2);

        integerColumn2.setColumnFilterable(true);
        integerColumn2.setColumnName("veiAno");
        integerColumn2.setColumnSortable(true);
        integerColumn2.setHeaderColumnName("Ano");
        integerColumn2.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(integerColumn2);

        textColumn3.setColumnFilterable(true);
        textColumn3.setColumnName("veiCor");
        textColumn3.setColumnSortable(true);
        textColumn3.setHeaderColumnName("Cor");
        textColumn3.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn3);

        textColumn4.setColumnFilterable(true);
        textColumn4.setColumnName("veiPlaca");
        textColumn4.setColumnSortable(true);
        textColumn4.setHeaderColumnName("Placa");
        textColumn4.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn4);

        integerColumn3.setColumnFilterable(true);
        integerColumn3.setColumnName("veiKm");
        integerColumn3.setColumnSortable(true);
        integerColumn3.setHeaderColumnName("Km ");
        gridControl1.getColumnContainer().add(integerColumn3);

        dateColumn1.setColumnFilterable(true);
        dateColumn1.setColumnName("veiData");
        dateColumn1.setColumnSortable(true);
        dateColumn1.setHeaderColumnName("Data");
        gridControl1.getColumnContainer().add(dateColumn1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        insertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(insertButton1);
        jPanel1.add(reloadButton1);

        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        labelControl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelControl2.setLabel("Cadastro de Veículos");
        jPanel2.add(labelControl2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
        new VeiculoDetalheController(this, null, conn);
    }//GEN-LAST:event_insertButton1ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateColumn1;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn2;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    // End of variables declaration//GEN-END:variables
}
