/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.jumbo.frame;





import br.com.jumbo.controller.ViagensControler;
import br.com.jumbo.controller.ViagensDetalheController;
import conecxao.AcessoBD;
import java.security.Principal;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Joao
 */
public class Viagens extends InternalFrame {
    

    /**
     * Creates new form Carros
     */

        private Connection conn = null;

    public Viagens(Connection conn, ViagensControler controller) {
        this.conn = conn;

        try {

            initComponents();
            setSize(500, 200);
            gridControl1.setController(controller);
            gridControl1.setGridDataLocator(controller);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void reloadData() {
        
        gridControl1.reloadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gridControl1 = new org.openswing.swing.client.GridControl();
        integerColumn1 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        dateColumn1 = new org.openswing.swing.table.columns.client.DateColumn();
        dateColumn2 = new org.openswing.swing.table.columns.client.DateColumn();
        decimalColumn1 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn2 = new org.openswing.swing.table.columns.client.DecimalColumn();
        integerColumn2 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn3 = new org.openswing.swing.table.columns.client.DecimalColumn();
        textColumn7 = new org.openswing.swing.table.columns.client.TextColumn();
        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        jPanel2 = new javax.swing.JPanel();
        labelControl2 = new org.openswing.swing.client.LabelControl();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setFunctionId("viagens");
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl1.setValueObjectClassName("br.com.jumbo.vo.ViagensVO");

        integerColumn1.setColumnFilterable(true);
        integerColumn1.setColumnName("codVi");
        integerColumn1.setColumnSortable(true);
        integerColumn1.setHeaderColumnName("Código ");
        integerColumn1.setPreferredWidth(80);
        gridControl1.getColumnContainer().add(integerColumn1);

        textColumn2.setColumnFilterable(true);
        textColumn2.setColumnName("veiculoVeiPlaca");
        textColumn2.setColumnSortable(true);
        textColumn2.setHeaderColumnName("Placa");
        textColumn2.setHeaderFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        textColumn2.setPreferredWidth(80);
        textColumn2.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn2);

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("colNome");
        textColumn1.setColumnSortable(true);
        textColumn1.setHeaderColumnName("Nome");
        textColumn1.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn3.setColumnFilterable(true);
        textColumn3.setColumnName("viLocCar");
        textColumn3.setColumnSortable(true);
        textColumn3.setHeaderColumnName("Local Carregamento");
        textColumn3.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn3);

        textColumn4.setColumnFilterable(true);
        textColumn4.setColumnName("viLocDes");
        textColumn4.setColumnSortable(true);
        textColumn4.setHeaderColumnName("Local Descarga");
        textColumn4.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn4);

        dateColumn1.setColumnFilterable(true);
        dateColumn1.setColumnName("viDataCar");
        dateColumn1.setColumnSortable(true);
        dateColumn1.setHeaderColumnName("Data Carregamento");
        gridControl1.getColumnContainer().add(dateColumn1);

        dateColumn2.setColumnFilterable(true);
        dateColumn2.setColumnName("viDataDes");
        dateColumn2.setColumnSortable(true);
        dateColumn2.setHeaderColumnName("Data Descarga");
        gridControl1.getColumnContainer().add(dateColumn2);

        decimalColumn1.setColumnFilterable(true);
        decimalColumn1.setColumnName("viValorTon");
        decimalColumn1.setColumnSortable(true);
        decimalColumn1.setDecimals(2);
        decimalColumn1.setHeaderColumnName("Valor Ton");
        gridControl1.getColumnContainer().add(decimalColumn1);

        decimalColumn2.setColumnFilterable(true);
        decimalColumn2.setColumnName("viPesoTotal");
        decimalColumn2.setColumnSortable(true);
        decimalColumn2.setDecimals(3);
        decimalColumn2.setHeaderColumnName("Peso");
        gridControl1.getColumnContainer().add(decimalColumn2);

        integerColumn2.setColumnFilterable(true);
        integerColumn2.setColumnName("viNumNf");
        integerColumn2.setColumnSortable(true);
        integerColumn2.setHeaderColumnName("Número NF");
        gridControl1.getColumnContainer().add(integerColumn2);

        textColumn5.setColumnFilterable(true);
        textColumn5.setColumnName("viObs");
        textColumn5.setColumnSortable(true);
        textColumn5.setHeaderColumnName("Observações");
        gridControl1.getColumnContainer().add(textColumn5);

        textColumn6.setColumnFilterable(true);
        textColumn6.setColumnName("proNome");
        textColumn6.setColumnSortable(true);
        textColumn6.setHeaderColumnName("Produto");
        textColumn6.setTextAlignment(SwingConstants.CENTER);
        gridControl1.getColumnContainer().add(textColumn6);

        decimalColumn3.setColumnFilterable(true);
        decimalColumn3.setColumnName("viValorTotal");
        decimalColumn3.setColumnSortable(true);
        decimalColumn3.setDecimals(2);
        decimalColumn3.setHeaderColumnName("Valor Total");
        gridControl1.getColumnContainer().add(decimalColumn3);

        textColumn7.setColumnFilterable(true);
        textColumn7.setColumnName("viMesRef");
        textColumn7.setColumnSortable(true);
        textColumn7.setHeaderColumnName("MÊS");
        gridControl1.getColumnContainer().add(textColumn7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        insertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(insertButton1);
        jPanel1.add(reloadButton1);
        jPanel1.add(deleteButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        labelControl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelControl2.setLabel("Cadastro de Viagens");
        jPanel2.add(labelControl2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
       new ViagensDetalheController(this, null, conn);
    }//GEN-LAST:event_insertButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateColumn1;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn1;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn3;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn7;
    // End of variables declaration//GEN-END:variables
}
